- hosts: all
  sudo: true
  roles:
    - base

- hosts: webservers
  sudo: true
  roles:
    - { role: webserver, nginx_lb: True }
    - role: nginx
      nginx_http_params:
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
          - listen 80
          - location / { proxy_pass http://default; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for

          
- hosts: appservers
  sudo: true
  roles:
    - webserver
    - role: nginx
      nginx_http_params:
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
          - listen 8080
          - root /usr/share/nginx/html
    - static_app
          
- hosts: monitoring
  roles:
    - monitoring
