---
- include: lb.yml
  when: nginx_lb == True

- name: Install packages
  sudo: yes
  apt: package={{ item }} state=present update_cache=yes
  with_items:
    - nagios-nrpe-server
    - nagios-plugins


- name: Services enables/started
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nagios-nrpe-server

      
#- name: deploy iptables rules
#  template: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables

